// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bfs_gas_bfs_gas,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.896000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=291,HLS_SYN_LUT=6056,HLS_VERSION=2022_2}" *)

module bfs_gas (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] source;
wire   [31:0] num_nodes;
reg   [15:0] distances_0_address0;
reg    distances_0_ce0;
reg    distances_0_we0;
reg   [31:0] distances_0_d0;
reg   [19:0] visited_1_address1;
reg    visited_1_ce1;
reg    visited_1_we1;
reg   [0:0] visited_1_d1;
reg   [15:0] distances_1_address0;
reg    distances_1_ce0;
reg    distances_1_we0;
reg   [31:0] distances_1_d0;
reg   [15:0] distances_2_address0;
reg    distances_2_ce0;
reg    distances_2_we0;
reg   [31:0] distances_2_d0;
reg   [15:0] distances_3_address0;
reg    distances_3_ce0;
reg    distances_3_we0;
reg   [31:0] distances_3_d0;
reg   [15:0] distances_4_address0;
reg    distances_4_ce0;
reg    distances_4_we0;
reg   [31:0] distances_4_d0;
reg   [15:0] distances_5_address0;
reg    distances_5_ce0;
reg    distances_5_we0;
reg   [31:0] distances_5_d0;
reg   [15:0] distances_6_address0;
reg    distances_6_ce0;
reg    distances_6_we0;
reg   [31:0] distances_6_d0;
reg   [15:0] distances_7_address0;
reg    distances_7_ce0;
reg    distances_7_we0;
reg   [31:0] distances_7_d0;
reg   [15:0] distances_8_address0;
reg    distances_8_ce0;
reg    distances_8_we0;
reg   [31:0] distances_8_d0;
reg   [15:0] distances_9_address0;
reg    distances_9_ce0;
reg    distances_9_we0;
reg   [31:0] distances_9_d0;
reg   [15:0] distances_10_address0;
reg    distances_10_ce0;
reg    distances_10_we0;
reg   [31:0] distances_10_d0;
reg   [15:0] distances_11_address0;
reg    distances_11_ce0;
reg    distances_11_we0;
reg   [31:0] distances_11_d0;
reg   [15:0] distances_12_address0;
reg    distances_12_ce0;
reg    distances_12_we0;
reg   [31:0] distances_12_d0;
reg   [15:0] distances_13_address0;
reg    distances_13_ce0;
reg    distances_13_we0;
reg   [31:0] distances_13_d0;
reg   [15:0] distances_14_address0;
reg    distances_14_ce0;
reg    distances_14_we0;
reg   [31:0] distances_14_d0;
reg   [15:0] distances_15_address0;
reg    distances_15_ce0;
reg    distances_15_we0;
reg   [31:0] distances_15_d0;
reg   [31:0] num_nodes_read_reg_468;
reg   [31:0] source_read_reg_473;
reg   [15:0] lshr_ln_reg_478;
wire   [3:0] trunc_ln28_fu_441_p1;
reg   [3:0] trunc_ln28_reg_483;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_done;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_idle;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_ready;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_d0;
wire   [19:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_address1;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_ce1;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_we1;
wire   [0:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_d1;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_d0;
wire   [15:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_address0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_ce0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_we0;
wire   [31:0] grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_d0;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_idle;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_ready;
wire    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_in_stream_TREADY;
reg    grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln541_fu_445_p1;
wire   [63:0] zext_ln28_fu_449_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_in_stream_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg = 1'b0;
#0 grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg = 1'b0;
end

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_0_address0),
    .ce0(distances_0_ce0),
    .we0(distances_0_we0),
    .d0(distances_0_d0)
);

bfs_gas_visited_1_RAM_2P_BRAM_0R0W #(
    .DataWidth( 1 ),
    .AddressRange( 1000000 ),
    .AddressWidth( 20 ))
visited_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address1(visited_1_address1),
    .ce1(visited_1_ce1),
    .we1(visited_1_we1),
    .d1(visited_1_d1)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_1_address0),
    .ce0(distances_1_ce0),
    .we0(distances_1_we0),
    .d0(distances_1_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_2_address0),
    .ce0(distances_2_ce0),
    .we0(distances_2_we0),
    .d0(distances_2_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_3_address0),
    .ce0(distances_3_ce0),
    .we0(distances_3_we0),
    .d0(distances_3_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_4_address0),
    .ce0(distances_4_ce0),
    .we0(distances_4_we0),
    .d0(distances_4_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_5_address0),
    .ce0(distances_5_ce0),
    .we0(distances_5_we0),
    .d0(distances_5_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_6_address0),
    .ce0(distances_6_ce0),
    .we0(distances_6_we0),
    .d0(distances_6_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_7_address0),
    .ce0(distances_7_ce0),
    .we0(distances_7_we0),
    .d0(distances_7_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_8_address0),
    .ce0(distances_8_ce0),
    .we0(distances_8_we0),
    .d0(distances_8_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_9_address0),
    .ce0(distances_9_ce0),
    .we0(distances_9_we0),
    .d0(distances_9_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_10_address0),
    .ce0(distances_10_ce0),
    .we0(distances_10_we0),
    .d0(distances_10_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_11_address0),
    .ce0(distances_11_ce0),
    .we0(distances_11_we0),
    .d0(distances_11_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_12_address0),
    .ce0(distances_12_ce0),
    .we0(distances_12_we0),
    .d0(distances_12_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_13_address0),
    .ce0(distances_13_ce0),
    .we0(distances_13_we0),
    .d0(distances_13_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_14_address0),
    .ce0(distances_14_ce0),
    .we0(distances_14_we0),
    .d0(distances_14_d0)
);

bfs_gas_distances_0_RAM_1P_URAM_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 62500 ),
    .AddressWidth( 16 ))
distances_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(distances_15_address0),
    .ce0(distances_15_ce0),
    .we0(distances_15_we0),
    .d0(distances_15_d0)
);

bfs_gas_bfs_gas_Pipeline_VITIS_LOOP_22_1 grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start),
    .ap_done(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_done),
    .ap_idle(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_idle),
    .ap_ready(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_ready),
    .num_nodes(num_nodes_read_reg_468),
    .distances_0_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_address0),
    .distances_0_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_ce0),
    .distances_0_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_we0),
    .distances_0_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_d0),
    .visited_1_address1(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_address1),
    .visited_1_ce1(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_ce1),
    .visited_1_we1(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_we1),
    .visited_1_d1(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_d1),
    .distances_1_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_address0),
    .distances_1_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_ce0),
    .distances_1_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_we0),
    .distances_1_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_d0),
    .distances_2_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_address0),
    .distances_2_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_ce0),
    .distances_2_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_we0),
    .distances_2_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_d0),
    .distances_3_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_address0),
    .distances_3_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_ce0),
    .distances_3_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_we0),
    .distances_3_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_d0),
    .distances_4_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_address0),
    .distances_4_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_ce0),
    .distances_4_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_we0),
    .distances_4_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_d0),
    .distances_5_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_address0),
    .distances_5_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_ce0),
    .distances_5_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_we0),
    .distances_5_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_d0),
    .distances_6_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_address0),
    .distances_6_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_ce0),
    .distances_6_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_we0),
    .distances_6_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_d0),
    .distances_7_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_address0),
    .distances_7_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_ce0),
    .distances_7_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_we0),
    .distances_7_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_d0),
    .distances_8_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_address0),
    .distances_8_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_ce0),
    .distances_8_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_we0),
    .distances_8_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_d0),
    .distances_9_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_address0),
    .distances_9_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_ce0),
    .distances_9_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_we0),
    .distances_9_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_d0),
    .distances_10_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_address0),
    .distances_10_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_ce0),
    .distances_10_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_we0),
    .distances_10_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_d0),
    .distances_11_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_address0),
    .distances_11_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_ce0),
    .distances_11_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_we0),
    .distances_11_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_d0),
    .distances_12_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_address0),
    .distances_12_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_ce0),
    .distances_12_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_we0),
    .distances_12_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_d0),
    .distances_13_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_address0),
    .distances_13_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_ce0),
    .distances_13_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_we0),
    .distances_13_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_d0),
    .distances_14_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_address0),
    .distances_14_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_ce0),
    .distances_14_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_we0),
    .distances_14_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_d0),
    .distances_15_address0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_address0),
    .distances_15_ce0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_ce0),
    .distances_15_we0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_we0),
    .distances_15_d0(grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_d0)
);

bfs_gas_bfs_gas_Pipeline_VITIS_LOOP_31_2 grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start),
    .ap_done(grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done),
    .ap_idle(grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_idle),
    .ap_ready(grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_in_stream_TREADY)
);

bfs_gas_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .source(source),
    .num_nodes(num_nodes),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

bfs_gas_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg <= 1'b1;
        end else if ((grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_ready == 1'b1)) begin
            grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg <= 1'b1;
        end else if ((grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_ready == 1'b1)) begin
            grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        lshr_ln_reg_478 <= {{source[19:4]}};
        num_nodes_read_reg_468 <= num_nodes;
        source_read_reg_473 <= source;
        trunc_ln28_reg_483 <= trunc_ln28_fu_441_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_0_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_0_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_address0;
    end else begin
        distances_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_0_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_ce0;
    end else begin
        distances_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_0_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_d0;
    end else begin
        distances_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd0))) begin
        distances_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_0_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_0_we0;
    end else begin
        distances_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_10_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_10_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_address0;
    end else begin
        distances_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_10_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_10_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_ce0;
    end else begin
        distances_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_10_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_10_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_d0;
    end else begin
        distances_10_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd10))) begin
        distances_10_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_10_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_10_we0;
    end else begin
        distances_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_11_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_11_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_address0;
    end else begin
        distances_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_11_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_11_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_ce0;
    end else begin
        distances_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_11_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_11_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_d0;
    end else begin
        distances_11_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd11))) begin
        distances_11_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_11_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_11_we0;
    end else begin
        distances_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_12_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_12_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_address0;
    end else begin
        distances_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_12_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_12_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_ce0;
    end else begin
        distances_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_12_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_12_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_d0;
    end else begin
        distances_12_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd12))) begin
        distances_12_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_12_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_12_we0;
    end else begin
        distances_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_13_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_13_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_address0;
    end else begin
        distances_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_13_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_13_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_ce0;
    end else begin
        distances_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_13_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_13_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_d0;
    end else begin
        distances_13_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd13))) begin
        distances_13_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_13_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_13_we0;
    end else begin
        distances_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_14_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_14_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_address0;
    end else begin
        distances_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_14_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_14_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_ce0;
    end else begin
        distances_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_14_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_14_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_d0;
    end else begin
        distances_14_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd14))) begin
        distances_14_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_14_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_14_we0;
    end else begin
        distances_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_15_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_15_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_address0;
    end else begin
        distances_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_15_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_15_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_ce0;
    end else begin
        distances_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_15_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_15_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_d0;
    end else begin
        distances_15_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd15))) begin
        distances_15_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_15_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_15_we0;
    end else begin
        distances_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_1_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_1_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_address0;
    end else begin
        distances_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_1_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_ce0;
    end else begin
        distances_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_1_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_d0;
    end else begin
        distances_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd1))) begin
        distances_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_1_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_1_we0;
    end else begin
        distances_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_2_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_2_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_address0;
    end else begin
        distances_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_2_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_ce0;
    end else begin
        distances_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_2_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_d0;
    end else begin
        distances_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd2))) begin
        distances_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_2_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_2_we0;
    end else begin
        distances_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_3_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_3_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_address0;
    end else begin
        distances_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_3_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_ce0;
    end else begin
        distances_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_3_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_d0;
    end else begin
        distances_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd3))) begin
        distances_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_3_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_3_we0;
    end else begin
        distances_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_4_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_4_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_address0;
    end else begin
        distances_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_4_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_ce0;
    end else begin
        distances_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_4_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_4_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_d0;
    end else begin
        distances_4_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd4))) begin
        distances_4_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_4_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_4_we0;
    end else begin
        distances_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_5_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_5_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_address0;
    end else begin
        distances_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_5_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_ce0;
    end else begin
        distances_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_5_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_5_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_d0;
    end else begin
        distances_5_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd5))) begin
        distances_5_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_5_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_5_we0;
    end else begin
        distances_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_6_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_6_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_address0;
    end else begin
        distances_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_6_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_ce0;
    end else begin
        distances_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_6_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_6_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_d0;
    end else begin
        distances_6_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd6))) begin
        distances_6_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_6_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_6_we0;
    end else begin
        distances_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_7_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_7_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_address0;
    end else begin
        distances_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_7_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_ce0;
    end else begin
        distances_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_7_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_7_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_d0;
    end else begin
        distances_7_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd7))) begin
        distances_7_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_7_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_7_we0;
    end else begin
        distances_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_8_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_8_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_address0;
    end else begin
        distances_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_8_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_8_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_ce0;
    end else begin
        distances_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_8_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_8_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_d0;
    end else begin
        distances_8_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd8))) begin
        distances_8_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_8_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_8_we0;
    end else begin
        distances_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_9_address0 = zext_ln28_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_9_address0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_address0;
    end else begin
        distances_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_9_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_9_ce0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_ce0;
    end else begin
        distances_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_9_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_9_d0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_d0;
    end else begin
        distances_9_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln28_reg_483 == 4'd9))) begin
        distances_9_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_9_we0 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_distances_9_we0;
    end else begin
        distances_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_stream_TREADY_int_regslice = grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        visited_1_address1 = zext_ln541_fu_445_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        visited_1_address1 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_address1;
    end else begin
        visited_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        visited_1_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        visited_1_ce1 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_ce1;
    end else begin
        visited_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        visited_1_d1 = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        visited_1_d1 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_d1;
    end else begin
        visited_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        visited_1_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        visited_1_we1 = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_visited_1_we1;
    end else begin
        visited_1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start = grp_bfs_gas_Pipeline_VITIS_LOOP_22_1_fu_386_ap_start_reg;

assign grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start = grp_bfs_gas_Pipeline_VITIS_LOOP_31_2_fu_425_ap_start_reg;

assign in_stream_TREADY = regslice_both_in_stream_U_ack_in;

assign trunc_ln28_fu_441_p1 = source[3:0];

assign zext_ln28_fu_449_p1 = lshr_ln_reg_478;

assign zext_ln541_fu_445_p1 = source_read_reg_473;

endmodule //bfs_gas
